<a href="https://colab.research.google.com/github/mayur200654321/Artificial_Intelligence_Lab_SE_A_65/blob/master/DS%20exp3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Create a 3x3 matrix
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 10]])

# Compute determinant
det_A = np.linalg.det(A)

print("Matrix A:\n", A)
print("Determinant of A:", det_A)

Matrix A:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]
Determinant of A: -2.9999999999999996


In [2]:
# Compute inverse (only if determinant is not zero)
if det_A != 0:
    inv_A = np.linalg.inv(A)
    print("Inverse of A:\n", inv_A)
else:
    print("Matrix is singular and cannot be inverted.")

Inverse of A:
 [[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]


In [3]:
# Coefficient matrix
C = np.array([[2, 3],
              [4, 5]])

# Constant matrix
D = np.array([10, 20])

# Solve the system
solution = np.linalg.solve(C, D)

print("Solution (x, y):", solution)

Solution (x, y): [5. 0.]
